
# This file is automatically generated, you probably don't want to edit this

CVIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CVIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL, ...) {

            super$initialize(
                package="cviJmv",
                name="CVI",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep)

            self$.addOption(private$..dep)
        }),
    active = list(
        dep = function() private$..dep$value),
    private = list(
        ..dep = NA)
)

CVIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CVIResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        cviTable = function() private$.items[["cviTable"]],
        propTable = function() private$.items[["propTable"]],
        scoreTable2 = function() private$.items[["scoreTable2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Content Validity Index Calculation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Content Validity Index Calculation"))
            self$add(jmvcore::Table$new(
                options=options,
                name="cviTable",
                title="CVI Table",
                rows=5,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="varSCVI", 
                        `title`="Average", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="propTable",
                title="Proportion Relevance of Experts",
                rows=0,
                columns=list(
                    list(
                        `name`="Expert", 
                        `title`="Expert", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `title`="PR Score", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="scoreTable2",
                title="Score Table",
                rows=0,
                columns=list(
                    list(
                        `name`="Item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="eA", 
                        `title`="Experts in Agreement", 
                        `type`="number"),
                    list(
                        `name`="iCvi", 
                        `title`="I-CVI", 
                        `type`="number"),
                    list(
                        `name`="uA", 
                        `title`="UA", 
                        `type`="number"))))}))

CVIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CVIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "cviJmv",
                name = "CVI",
                version = c(1,0,0),
                options = options,
                results = CVIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Content Validity Index Calculation
#'
#' 
#' @param data .
#' @param dep .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cviTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$propTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scoreTable2} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cviTable$asDF}
#'
#' \code{as.data.frame(results$cviTable)}
#'
#' @export
CVI <- function(
    data,
    dep) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CVI requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- CVIOptions$new(
        dep = dep)

    analysis <- CVIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

