
# This file is automatically generated, you probably don't want to edit this

CVIOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CVIOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL, ...) {

            super$initialize(
                package="cviJmv",
                name="CVI",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep)

            self$.addOption(private$..dep)
        }),
    active = list(
        dep = function() private$..dep$value),
    private = list(
        ..dep = NA)
)

CVIResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CVIResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Content Validity Index Calculation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Content Validity Index Calculation"))}))

CVIBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CVIBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "cviJmv",
                name = "CVI",
                version = c(1,0,0),
                options = options,
                results = CVIResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Content Validity Index Calculation
#'
#' 
#' @param data .
#' @param dep .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
CVI <- function(
    data,
    dep) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CVI requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- CVIOptions$new(
        dep = dep)

    analysis <- CVIClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

